# Generated by Django 5.2.3 on 2025-06-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domofon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domofoncall',
            name='open_closed',
            field=models.BooleanField(default=False, verbose_name='Открытие двери'),
        ),
    ]
