# Generated by Django 5.2.3 on 2025-06-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domofon', '0002_domofoncall_open_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domofoncall',
            name='open_closed',
        ),
    ]
