# Generated by Django 5.2.3 on 2025-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domofon', '0005_remove_domofoncall_open_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='domofoncall',
            name='open_closed',
            field=models.BooleanField(default=False, verbose_name='Открытие двери'),
        ),
    ]
