# Generated by Django 5.2.3 on 2025-06-26 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomofonCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC адрес домофона')),
                ('apartment_number', models.PositiveIntegerField(verbose_name='Номер квартиры')),
                ('call_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время звонка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Домофон включен')),
            ],
            options={
                'verbose_name': 'MAC адрес домофона',
                'verbose_name_plural': 'MAC адрес домофона',
            },
        ),
    ]
